### PR TITLE
Project Start: Get list of tweets from a twitter account

### PR DESCRIPTION
**Pull request by Charlotteis**
This Pull Request does the following: if you run `node index.js` within the directory of this repository (folder), you will get a list of tweets back from the [@yourfirstpr](http://twitter.com/yourfirstpr) twitter account.

It uses the [twitter](https://www.npmjs.com/package/twitter) node module. It sends my credentials (not stored here as you should [never store private information in GitHub](https://help.github.com/articles/remove-sensitive-data/)) to Twitter and gets back the list of tweets. In it's initial state, Twitter returns a whole bunch of data but I only want to get the text of a tweet, which I do with 'tweet.text'.

This is the first step of this project, to find out more about it: check out the README within this PR.

🎉

### CODE REVIEW

**Comment by nzall** [comment]
Keep the paradigms of API calls and output in separate functions. Instead of doing console.log() in your function that retrieves the tweets, a better idea would be to return the tweets using a promise and let the function that requested the API call know what to do with them.

According to the readme, eventually you want to open any links in those tweets. Suppose that at another time, you want to do something else with those tweets. if you tightly couple the output with the API call to twitter, you will have to either repeat the code or write conditionals to deal with the extra action possibilities. If you just returns the tweets, you can reuse the API calls and don't need to touch any of the other code.

**Comment by Charlotteis** [comment]
Hi @nzall, thanks for taking some time out to respond.

I was thinking something like:

```diff
- client.get('statuses/user_timeline', params, function (error, tweets, response) {
-  if (error) {
-    console.log(error)
-  }
-
-  tweets.forEach(function (tweet) {
-    console.log(tweet.text)
-  })
-})

+ var tweets = client.get('statuses/user_timeline', params, function (error, tweets, response) {
+   if (error) {
+    console.log(error)
+   }
+ })
+
+ tweets.forEach(function (tweet) {
+    console.log(tweet.text)
+ })

I'm a junior developer so I'm not as experienced as I'd like to be, but I hope this is an improvement :)

**Comment by HugoGiraudel** [comment]
Actually a decent API would probably look like something like this:

```javascript
// Perform the request and expect a promise back
var request = client.get('statuses/user_timeline', params);

// Whenever you get some result, do whatever you want with them
request.then(function (tweets) {
  // Do whatever you want with `tweets`
});
```

This way the fetching is completely decoupled from the data manipulation (whatever could it be: printing, storing, etc.). Does that make any sense?

**Comment by Charlotteis** [comment]
Thank you @HugoGiraudel! Promises is something I've never encountered before so I am reading up on them now (http://www.html5rocks.com/en/tutorials/es6/promises/), I think I'll end up using the Bluebird library for node: https://github.com/petkaantonov/bluebird.

**Comment by imjacobclark** [comment]
@Charlotteis Promises are native in Node.js v4 (io.js)! Or if you're running Node.js 0.10+ you can pass the `--harmony` and run them natively also!

**Comment by Charlotteis** [comment]
> Promises are native in Node.js v4 (io.js)! Or if you're running Node.js 0.10+ you can pass the --harmony and run them natively also!

Oh! I've just upgraded to v4. I will try and find the relevant docs for that, thanks!

**Comment by imjacobclark** [comment]
@Charlotteis https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by Charlotteis** [comment]
Okay I think I have massively improved this now with the use of Promises and modules so I feel good about merging this! Thank you @imjacobclark @HugoGiraudel & @nzall :)

:tada:

**Pull request merged**
